name: alarm_test_case
description: Alarm App Test Case Stockbit


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  dartz: ^0.10.1
  get_it: ^7.2.0
  flutter_bloc: ^7.3.0
  pedantic:
  fluttertoast: ^8.0.8
  flutter_local_notifications: ^7.0.0
  flutter_native_timezone: ^2.0.0
  rxdart:
  sqflite:
  path_provider:

  #lib for create chart
  d_chart: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
